title:       "Operating Systems 2021-2 (OS212)"
version:     "0004---15-Jun-2021"
copyright:   "2021-2021"
description: >- 
  OS212
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Cicak Bin Kadal"
address:          "Pamulang"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://ui-fasilkom-os.github.io/UF-os212/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/UI-FASILKOM-OS/UF-os212/"
urlghpage:        "https://ui-fasilkom-os.github.io/UF-os212/"
keywords:         "jekyll, testing"
github:           [metadata]

